"""Add chore and chore assignment models

Revision ID: 0bf2f56c7c7b
Revises: 1279218f85f1
Create Date: 2025-10-05 18:15:06.636476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bf2f56c7c7b'
down_revision = '1279218f85f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chore_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_of', sa.Date(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('chore_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chore_id'], ['chore.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chore_assignment')
    op.drop_table('chore')
    # ### end Alembic commands ###
