"""Add is_pinned to Note model

Revision ID: 0ca2b01fe117
Revises: 11faf77f8b21
Create Date: 2025-09-16 18:08:33.403993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ca2b01fe117'
down_revision = '11faf77f8b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pinned', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('is_pinned')

    # ### end Alembic commands ###
