"""Implement Family Spaces architecture

Revision ID: 11faf77f8b21
Revises: 2c0407ab5708
Create Date: 2025-09-15 12:51:03.648445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11faf77f8b21'
down_revision = '2c0407ab5708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'family_id')
    )
    op.drop_table('list_members')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('event_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'family', ['family_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'])

    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('meal_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'])
        batch_op.create_foreign_key(None, 'family', ['family_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('note_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'family', ['family_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('shopping_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('shopping_list_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'family', ['family_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('shopping_list_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.drop_column('family_id')

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('note_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.drop_column('author_id')
        batch_op.drop_column('family_id')

    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('meal_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.drop_column('author_id')
        batch_op.drop_column('family_id')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('author_id')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('event_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.drop_column('author_id')
        batch_op.drop_column('family_id')

    op.create_table('list_members',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('list_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['shopping_list.id'], name=op.f('list_members_list_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('list_members_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'list_id', name=op.f('list_members_pkey'))
    )
    op.drop_table('family_members')
    op.drop_table('family')
    # ### end Alembic commands ###
