"""Add week_of date to Meal model

Revision ID: 845d594b411d
Revises: 2d21d2fb1370
Create Date: 2025-10-18 18:06:12.857802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845d594b411d'
down_revision = '2d21d2fb1370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_of', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.drop_column('week_of')

    # ### end Alembic commands ###
