"""Add points to Chore model

Revision ID: f3fadfb356a4
Revises: 5b7a397e9c83
Create Date: 2025-10-09 15:12:37.994801

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f3fadfb356a4"
down_revision = "5b7a397e9c83"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chore", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("points", sa.Integer(), nullable=False, server_default="5")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chore", schema=None) as batch_op:
        batch_op.drop_column("points")

    # ### end Alembic commands ###
